// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UserCenter.proto

package ApiRPC

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientInfo struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AuthKey              string   `protobuf:"bytes,3,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98e8acf3c37663a, []int{0}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ClientInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClientInfo) GetAuthKey() string {
	if m != nil {
		return m.AuthKey
	}
	return ""
}

type AuthToken struct {
	Token                string      `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ClientInfo           *ClientInfo `protobuf:"bytes,2,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AuthToken) Reset()         { *m = AuthToken{} }
func (m *AuthToken) String() string { return proto.CompactTextString(m) }
func (*AuthToken) ProtoMessage()    {}
func (*AuthToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98e8acf3c37663a, []int{1}
}

func (m *AuthToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthToken.Unmarshal(m, b)
}
func (m *AuthToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthToken.Marshal(b, m, deterministic)
}
func (m *AuthToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthToken.Merge(m, src)
}
func (m *AuthToken) XXX_Size() int {
	return xxx_messageInfo_AuthToken.Size(m)
}
func (m *AuthToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthToken.DiscardUnknown(m)
}

var xxx_messageInfo_AuthToken proto.InternalMessageInfo

func (m *AuthToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthToken) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

type TokenCheckResult struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenCheckResult) Reset()         { *m = TokenCheckResult{} }
func (m *TokenCheckResult) String() string { return proto.CompactTextString(m) }
func (*TokenCheckResult) ProtoMessage()    {}
func (*TokenCheckResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98e8acf3c37663a, []int{2}
}

func (m *TokenCheckResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenCheckResult.Unmarshal(m, b)
}
func (m *TokenCheckResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenCheckResult.Marshal(b, m, deterministic)
}
func (m *TokenCheckResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenCheckResult.Merge(m, src)
}
func (m *TokenCheckResult) XXX_Size() int {
	return xxx_messageInfo_TokenCheckResult.Size(m)
}
func (m *TokenCheckResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenCheckResult.DiscardUnknown(m)
}

var xxx_messageInfo_TokenCheckResult proto.InternalMessageInfo

func (m *TokenCheckResult) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*ClientInfo)(nil), "ApiRPC.ClientInfo")
	proto.RegisterType((*AuthToken)(nil), "ApiRPC.AuthToken")
	proto.RegisterType((*TokenCheckResult)(nil), "ApiRPC.TokenCheckResult")
}

func init() { proto.RegisterFile("UserCenter.proto", fileDescriptor_f98e8acf3c37663a) }

var fileDescriptor_f98e8acf3c37663a = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xa9, 0xd5, 0xd4, 0x4e, 0x41, 0xea, 0x20, 0x18, 0x3d, 0x49, 0x4e, 0x82, 0x90, 0x43,
	0x7b, 0xf6, 0x50, 0x72, 0x2a, 0x3d, 0x28, 0x8b, 0x7a, 0x0d, 0x35, 0x9d, 0xb2, 0x4b, 0xea, 0x6e,
	0xd9, 0x9d, 0x3d, 0xf4, 0xdf, 0xcb, 0x4e, 0x6c, 0x02, 0xde, 0xde, 0xfb, 0x60, 0xdf, 0x7b, 0x3b,
	0x30, 0xff, 0x0c, 0xe4, 0x2b, 0xb2, 0x4c, 0xbe, 0x3c, 0x7a, 0xc7, 0x0e, 0xb3, 0xd5, 0xd1, 0xa8,
	0xf7, 0xaa, 0x78, 0x03, 0xa8, 0x0e, 0x86, 0x2c, 0xaf, 0xed, 0xde, 0x21, 0xc2, 0xa5, 0x76, 0x81,
	0xf3, 0xd1, 0xd3, 0xe8, 0x79, 0xaa, 0x44, 0x27, 0x66, 0xb7, 0x3f, 0x94, 0x5f, 0x74, 0x2c, 0x69,
	0x7c, 0x80, 0xeb, 0x6d, 0x64, 0x5d, 0xb7, 0x74, 0xca, 0xc7, 0xc2, 0x27, 0xc9, 0x6f, 0xe8, 0x54,
	0x7c, 0xc1, 0x74, 0x15, 0x59, 0x7f, 0xb8, 0x96, 0x2c, 0xde, 0xc1, 0x15, 0x27, 0xf1, 0x17, 0xd8,
	0x19, 0x5c, 0xc2, 0xac, 0x91, 0xce, 0xda, 0xd8, 0xbd, 0x93, 0xe0, 0xd9, 0x02, 0xcb, 0x6e, 0x51,
	0x39, 0xcc, 0x51, 0xd0, 0xf4, 0xba, 0x78, 0x81, 0xb9, 0x64, 0x56, 0x9a, 0x9a, 0x56, 0x51, 0x88,
	0x07, 0xc6, 0x7b, 0x98, 0xc4, 0x40, 0xbe, 0x36, 0x3b, 0x29, 0x18, 0xab, 0x2c, 0xd9, 0xf5, 0x6e,
	0xb1, 0x01, 0x18, 0x7e, 0x8c, 0xaf, 0x70, 0x23, 0xaf, 0x86, 0x5d, 0xb7, 0xe7, 0xb2, 0x1e, 0x3d,
	0xe6, 0x67, 0xf4, 0xbf, 0xe5, 0x3b, 0x93, 0x8b, 0x2d, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x5c,
	0xf6, 0x6c, 0x15, 0x45, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserCenterClient is the client API for UserCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserCenterClient interface {
	CheckAuthToken(ctx context.Context, in *AuthToken, opts ...grpc.CallOption) (*TokenCheckResult, error)
}

type userCenterClient struct {
	cc *grpc.ClientConn
}

func NewUserCenterClient(cc *grpc.ClientConn) UserCenterClient {
	return &userCenterClient{cc}
}

func (c *userCenterClient) CheckAuthToken(ctx context.Context, in *AuthToken, opts ...grpc.CallOption) (*TokenCheckResult, error) {
	out := new(TokenCheckResult)
	err := c.cc.Invoke(ctx, "/ApiRPC.UserCenter/CheckAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCenterServer is the server API for UserCenter service.
type UserCenterServer interface {
	CheckAuthToken(context.Context, *AuthToken) (*TokenCheckResult, error)
}

// UnimplementedUserCenterServer can be embedded to have forward compatible implementations.
type UnimplementedUserCenterServer struct {
}

func (*UnimplementedUserCenterServer) CheckAuthToken(ctx context.Context, req *AuthToken) (*TokenCheckResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAuthToken not implemented")
}

func RegisterUserCenterServer(s *grpc.Server, srv UserCenterServer) {
	s.RegisterService(&_UserCenter_serviceDesc, srv)
}

func _UserCenter_CheckAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCenterServer).CheckAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ApiRPC.UserCenter/CheckAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCenterServer).CheckAuthToken(ctx, req.(*AuthToken))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserCenter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ApiRPC.UserCenter",
	HandlerType: (*UserCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAuthToken",
			Handler:    _UserCenter_CheckAuthToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "UserCenter.proto",
}
