// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userCenter.proto

package ApiRPC

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// the check auth token message
type AuthToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthToken) Reset()         { *m = AuthToken{} }
func (m *AuthToken) String() string { return proto.CompactTextString(m) }
func (*AuthToken) ProtoMessage()    {}
func (*AuthToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_6169581d8008d4db, []int{0}
}

func (m *AuthToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthToken.Unmarshal(m, b)
}
func (m *AuthToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthToken.Marshal(b, m, deterministic)
}
func (m *AuthToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthToken.Merge(m, src)
}
func (m *AuthToken) XXX_Size() int {
	return xxx_messageInfo_AuthToken.Size(m)
}
func (m *AuthToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthToken.DiscardUnknown(m)
}

var xxx_messageInfo_AuthToken proto.InternalMessageInfo

func (m *AuthToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenCheckResult struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenCheckResult) Reset()         { *m = TokenCheckResult{} }
func (m *TokenCheckResult) String() string { return proto.CompactTextString(m) }
func (*TokenCheckResult) ProtoMessage()    {}
func (*TokenCheckResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_6169581d8008d4db, []int{1}
}

func (m *TokenCheckResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenCheckResult.Unmarshal(m, b)
}
func (m *TokenCheckResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenCheckResult.Marshal(b, m, deterministic)
}
func (m *TokenCheckResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenCheckResult.Merge(m, src)
}
func (m *TokenCheckResult) XXX_Size() int {
	return xxx_messageInfo_TokenCheckResult.Size(m)
}
func (m *TokenCheckResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenCheckResult.DiscardUnknown(m)
}

var xxx_messageInfo_TokenCheckResult proto.InternalMessageInfo

func (m *TokenCheckResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*AuthToken)(nil), "ApiRPC.AuthToken")
	proto.RegisterType((*TokenCheckResult)(nil), "ApiRPC.TokenCheckResult")
}

func init() { proto.RegisterFile("userCenter.proto", fileDescriptor_6169581d8008d4db) }

var fileDescriptor_6169581d8008d4db = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2d, 0x4e, 0x2d,
	0x72, 0x4e, 0xcd, 0x2b, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x73, 0x2c,
	0xc8, 0x0c, 0x0a, 0x70, 0x56, 0x52, 0xe4, 0xe2, 0x74, 0x2c, 0x2d, 0xc9, 0x08, 0xc9, 0xcf, 0x4e,
	0xcd, 0x13, 0x12, 0xe1, 0x62, 0x2d, 0x01, 0x31, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20,
	0x1c, 0x25, 0x25, 0x2e, 0x01, 0xb0, 0xb4, 0x73, 0x46, 0x6a, 0x72, 0x76, 0x50, 0x6a, 0x71, 0x69,
	0x4e, 0x89, 0x10, 0x1f, 0x17, 0x53, 0x7e, 0x36, 0x58, 0x19, 0x47, 0x10, 0x53, 0x7e, 0xb6, 0x91,
	0x37, 0x17, 0x57, 0x28, 0xdc, 0x0a, 0x21, 0x5b, 0x2e, 0x3e, 0xb0, 0x62, 0x84, 0xc9, 0x82, 0x7a,
	0x10, 0xfb, 0xf4, 0xe0, 0x42, 0x52, 0x12, 0x30, 0x21, 0x74, 0xc3, 0x93, 0xd8, 0xc0, 0x4e, 0x34,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xbf, 0x53, 0xfa, 0xb6, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserCenterClient is the client API for UserCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserCenterClient interface {
	CheckAuthToken(ctx context.Context, in *AuthToken, opts ...grpc.CallOption) (*TokenCheckResult, error)
}

type userCenterClient struct {
	cc *grpc.ClientConn
}

func NewUserCenterClient(cc *grpc.ClientConn) UserCenterClient {
	return &userCenterClient{cc}
}

func (c *userCenterClient) CheckAuthToken(ctx context.Context, in *AuthToken, opts ...grpc.CallOption) (*TokenCheckResult, error) {
	out := new(TokenCheckResult)
	err := c.cc.Invoke(ctx, "/ApiRPC.UserCenter/CheckAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCenterServer is the server API for UserCenter service.
type UserCenterServer interface {
	CheckAuthToken(context.Context, *AuthToken) (*TokenCheckResult, error)
}

// UnimplementedUserCenterServer can be embedded to have forward compatible implementations.
type UnimplementedUserCenterServer struct {
}

func (*UnimplementedUserCenterServer) CheckAuthToken(ctx context.Context, req *AuthToken) (*TokenCheckResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAuthToken not implemented")
}

func RegisterUserCenterServer(s *grpc.Server, srv UserCenterServer) {
	s.RegisterService(&_UserCenter_serviceDesc, srv)
}

func _UserCenter_CheckAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCenterServer).CheckAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ApiRPC.UserCenter/CheckAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCenterServer).CheckAuthToken(ctx, req.(*AuthToken))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserCenter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ApiRPC.UserCenter",
	HandlerType: (*UserCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAuthToken",
			Handler:    _UserCenter_CheckAuthToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userCenter.proto",
}
