// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mysqlBind.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryUserField int32

const (
	QueryUserField_ById    QueryUserField = 0
	QueryUserField_ByEmail QueryUserField = 1
	QueryUserField_ByName  QueryUserField = 2
)

var QueryUserField_name = map[int32]string{
	0: "ById",
	1: "ByEmail",
	2: "ByName",
}

var QueryUserField_value = map[string]int32{
	"ById":    0,
	"ByEmail": 1,
	"ByName":  2,
}

func (x QueryUserField) String() string {
	return proto.EnumName(QueryUserField_name, int32(x))
}

func (QueryUserField) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d28f1fa67868a9e4, []int{0}
}

type UpdateUserField int32

const (
	UpdateUserField_NameMobileGender UpdateUserField = 0
	UpdateUserField_Password         UpdateUserField = 1
)

var UpdateUserField_name = map[int32]string{
	0: "NameMobileGender",
	1: "Password",
}

var UpdateUserField_value = map[string]int32{
	"NameMobileGender": 0,
	"Password":         1,
}

func (x UpdateUserField) String() string {
	return proto.EnumName(UpdateUserField_name, int32(x))
}

func (UpdateUserField) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d28f1fa67868a9e4, []int{1}
}

type UserBasicInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Gender               int32    `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	CreateTime           string   `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBasicInfo) Reset()         { *m = UserBasicInfo{} }
func (m *UserBasicInfo) String() string { return proto.CompactTextString(m) }
func (*UserBasicInfo) ProtoMessage()    {}
func (*UserBasicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d28f1fa67868a9e4, []int{0}
}

func (m *UserBasicInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBasicInfo.Unmarshal(m, b)
}
func (m *UserBasicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBasicInfo.Marshal(b, m, deterministic)
}
func (m *UserBasicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBasicInfo.Merge(m, src)
}
func (m *UserBasicInfo) XXX_Size() int {
	return xxx_messageInfo_UserBasicInfo.Size(m)
}
func (m *UserBasicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBasicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserBasicInfo proto.InternalMessageInfo

func (m *UserBasicInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserBasicInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserBasicInfo) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserBasicInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserBasicInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserBasicInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserBasicInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type UserBasicInfoList struct {
	Users                []*UserBasicInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserBasicInfoList) Reset()         { *m = UserBasicInfoList{} }
func (m *UserBasicInfoList) String() string { return proto.CompactTextString(m) }
func (*UserBasicInfoList) ProtoMessage()    {}
func (*UserBasicInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d28f1fa67868a9e4, []int{1}
}

func (m *UserBasicInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBasicInfoList.Unmarshal(m, b)
}
func (m *UserBasicInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBasicInfoList.Marshal(b, m, deterministic)
}
func (m *UserBasicInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBasicInfoList.Merge(m, src)
}
func (m *UserBasicInfoList) XXX_Size() int {
	return xxx_messageInfo_UserBasicInfoList.Size(m)
}
func (m *UserBasicInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBasicInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_UserBasicInfoList proto.InternalMessageInfo

func (m *UserBasicInfoList) GetUsers() []*UserBasicInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

type QueryUserParams struct {
	FilterField          QueryUserField `protobuf:"varint,1,opt,name=filter_field,json=filterField,proto3,enum=pb.QueryUserField" json:"filter_field,omitempty"`
	Id                   int64          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string         `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string         `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryUserParams) Reset()         { *m = QueryUserParams{} }
func (m *QueryUserParams) String() string { return proto.CompactTextString(m) }
func (*QueryUserParams) ProtoMessage()    {}
func (*QueryUserParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d28f1fa67868a9e4, []int{2}
}

func (m *QueryUserParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserParams.Unmarshal(m, b)
}
func (m *QueryUserParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserParams.Marshal(b, m, deterministic)
}
func (m *QueryUserParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserParams.Merge(m, src)
}
func (m *QueryUserParams) XXX_Size() int {
	return xxx_messageInfo_QueryUserParams.Size(m)
}
func (m *QueryUserParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserParams proto.InternalMessageInfo

func (m *QueryUserParams) GetFilterField() QueryUserField {
	if m != nil {
		return m.FilterField
	}
	return QueryUserField_ById
}

func (m *QueryUserParams) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *QueryUserParams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *QueryUserParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateUserParams struct {
	UpdateField          UpdateUserField `protobuf:"varint,1,opt,name=update_field,json=updateField,proto3,enum=pb.UpdateUserField" json:"update_field,omitempty"`
	Id                   int64           `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string          `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string          `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Mobile               string          `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string          `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Gender               int32           `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateUserParams) Reset()         { *m = UpdateUserParams{} }
func (m *UpdateUserParams) String() string { return proto.CompactTextString(m) }
func (*UpdateUserParams) ProtoMessage()    {}
func (*UpdateUserParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d28f1fa67868a9e4, []int{3}
}

func (m *UpdateUserParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserParams.Unmarshal(m, b)
}
func (m *UpdateUserParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserParams.Marshal(b, m, deterministic)
}
func (m *UpdateUserParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserParams.Merge(m, src)
}
func (m *UpdateUserParams) XXX_Size() int {
	return xxx_messageInfo_UpdateUserParams.Size(m)
}
func (m *UpdateUserParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserParams proto.InternalMessageInfo

func (m *UpdateUserParams) GetUpdateField() UpdateUserField {
	if m != nil {
		return m.UpdateField
	}
	return UpdateUserField_NameMobileGender
}

func (m *UpdateUserParams) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateUserParams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserParams) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UpdateUserParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateUserParams) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.QueryUserField", QueryUserField_name, QueryUserField_value)
	proto.RegisterEnum("pb.UpdateUserField", UpdateUserField_name, UpdateUserField_value)
	proto.RegisterType((*UserBasicInfo)(nil), "pb.UserBasicInfo")
	proto.RegisterType((*UserBasicInfoList)(nil), "pb.UserBasicInfoList")
	proto.RegisterType((*QueryUserParams)(nil), "pb.QueryUserParams")
	proto.RegisterType((*UpdateUserParams)(nil), "pb.UpdateUserParams")
}

func init() { proto.RegisterFile("mysqlBind.proto", fileDescriptor_d28f1fa67868a9e4) }

var fileDescriptor_d28f1fa67868a9e4 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xed, 0x3a, 0xb1, 0x1b, 0xc6, 0x21, 0x71, 0x27, 0xa1, 0xb2, 0x7a, 0x21, 0xca, 0x85, 0xa8,
	0x87, 0x1c, 0x52, 0x05, 0x21, 0x51, 0x21, 0x61, 0x09, 0xaa, 0x48, 0x6d, 0x49, 0x5d, 0x7a, 0xae,
	0x9c, 0x78, 0x82, 0x56, 0xf2, 0x17, 0xbb, 0x0e, 0x95, 0xaf, 0xfc, 0x27, 0xf8, 0x1d, 0xfc, 0x24,
	0xe4, 0xb5, 0x6b, 0x6c, 0xd2, 0x4a, 0x45, 0xdc, 0x32, 0x6f, 0xe6, 0x4d, 0xde, 0xbe, 0x37, 0x32,
	0xf4, 0xc3, 0x4c, 0x7e, 0x0d, 0x1c, 0x1e, 0xf9, 0xd3, 0x44, 0xc4, 0x69, 0x8c, 0x5a, 0xb2, 0x1a,
	0xff, 0x64, 0xf0, 0xfc, 0x46, 0x92, 0x70, 0x3c, 0xc9, 0xd7, 0x8b, 0x68, 0x13, 0x63, 0x0f, 0x34,
	0xee, 0xdb, 0x6c, 0xc4, 0x26, 0x2d, 0x57, 0xe3, 0x3e, 0x22, 0xb4, 0x23, 0x2f, 0x24, 0x5b, 0x1b,
	0xb1, 0xc9, 0x33, 0x57, 0xfd, 0xc6, 0x43, 0x30, 0xc2, 0x78, 0xc5, 0x03, 0xb2, 0x5b, 0x0a, 0x2d,
	0x2b, 0x1c, 0x82, 0x4e, 0xa1, 0xc7, 0x03, 0xbb, 0xad, 0xe0, 0xa2, 0xc0, 0x23, 0xe8, 0x24, 0x9e,
	0x94, 0x77, 0xb1, 0xf0, 0x6d, 0x5d, 0x35, 0xaa, 0x3a, 0xdf, 0xf4, 0x85, 0x22, 0x9f, 0x84, 0x6d,
	0x8c, 0xd8, 0x44, 0x77, 0xcb, 0x0a, 0x5f, 0x82, 0xb9, 0x16, 0xe4, 0xa5, 0x74, 0x9b, 0xf2, 0x90,
	0xec, 0x7d, 0x45, 0x83, 0x02, 0xfa, 0xcc, 0x43, 0x1a, 0x9f, 0xc2, 0x41, 0x43, 0xf7, 0x39, 0x97,
	0x29, 0xbe, 0x02, 0x7d, 0x2b, 0x49, 0x48, 0x9b, 0x8d, 0x5a, 0x13, 0x73, 0x76, 0x30, 0x4d, 0x56,
	0xd3, 0xc6, 0x94, 0x5b, 0xf4, 0xc7, 0xdf, 0x19, 0xf4, 0xaf, 0xb6, 0x24, 0xb2, 0xbc, 0xbb, 0xf4,
	0x84, 0x17, 0x4a, 0x9c, 0x43, 0x77, 0xc3, 0x83, 0x94, 0xc4, 0xed, 0x86, 0x53, 0x50, 0x58, 0xd0,
	0x9b, 0x61, 0xbe, 0xa3, 0x1a, 0xfd, 0x98, 0x77, 0x5c, 0xb3, 0x98, 0x53, 0x45, 0xe9, 0x97, 0x56,
	0xf9, 0x55, 0x79, 0xd0, 0xaa, 0x7b, 0x70, 0xef, 0x62, 0xfb, 0x8f, 0x8b, 0xe3, 0x5f, 0x0c, 0xac,
	0x9b, 0xc4, 0xf7, 0x52, 0xaa, 0xa9, 0x78, 0x0d, 0xdd, 0xad, 0xc2, 0x1a, 0x2a, 0x06, 0xea, 0x25,
	0xd5, 0x6c, 0x29, 0xa3, 0x18, 0xfc, 0x4f, 0x19, 0xb5, 0x30, 0xf5, 0x46, 0x98, 0xf5, 0xd8, 0x8c,
	0x47, 0x63, 0xdb, 0xaf, 0xc7, 0x76, 0x7c, 0x02, 0xbd, 0xa6, 0x57, 0xd8, 0x81, 0xb6, 0x93, 0x2d,
	0x7c, 0x6b, 0x0f, 0x4d, 0xd8, 0x77, 0xb2, 0x0f, 0xb9, 0x0c, 0x8b, 0x21, 0x80, 0xe1, 0x64, 0x97,
	0x5e, 0x48, 0x96, 0x76, 0x3c, 0x87, 0xfe, 0x5f, 0x4f, 0xc3, 0x21, 0x58, 0x79, 0xf3, 0x42, 0x29,
	0x39, 0x53, 0xbb, 0xad, 0x3d, 0xec, 0x42, 0x67, 0x59, 0x2a, 0xb0, 0xd8, 0xec, 0x47, 0x0b, 0xac,
	0x8b, 0xec, 0xfa, 0xea, 0x3c, 0x3f, 0xe9, 0x6b, 0x12, 0xdf, 0xf8, 0x9a, 0x70, 0x06, 0x70, 0x49,
	0x77, 0x9f, 0x22, 0xb5, 0x0b, 0x77, 0x0f, 0xe0, 0x68, 0x17, 0xc2, 0x39, 0x98, 0x67, 0x94, 0x2a,
	0x2c, 0x5b, 0xf8, 0x38, 0x68, 0x24, 0x5e, 0xc4, 0xf2, 0x10, 0xed, 0x0d, 0xf4, 0x2a, 0x9a, 0x7a,
	0xd6, 0x93, 0x99, 0xa7, 0x15, 0x53, 0x16, 0x26, 0x3c, 0xcc, 0x7c, 0xb1, 0xc3, 0x54, 0x47, 0xfe,
	0x16, 0xac, 0xe5, 0x36, 0xad, 0x70, 0xa5, 0x79, 0xd8, 0xbc, 0x8f, 0xc7, 0xff, 0xfa, 0x1d, 0x0c,
	0x4a, 0xf2, 0xbd, 0x93, 0xff, 0xc6, 0x7f, 0x0f, 0x87, 0x3b, 0xfc, 0xe2, 0xf1, 0x4f, 0x5d, 0xb1,
	0x32, 0xd4, 0xd7, 0xe7, 0xe4, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0x09, 0x8b, 0x05, 0x90,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MySQLBindServiceClient is the client API for MySQLBindService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MySQLBindServiceClient interface {
	NewOneUser(ctx context.Context, in *UserBasicInfo, opts ...grpc.CallOption) (*UserBasicInfo, error)
	GetUserById(ctx context.Context, in *QueryUserParams, opts ...grpc.CallOption) (*UserBasicInfo, error)
	GetUserByEmail(ctx context.Context, in *QueryUserParams, opts ...grpc.CallOption) (*UserBasicInfo, error)
	GetUsersByName(ctx context.Context, in *QueryUserParams, opts ...grpc.CallOption) (*UserBasicInfoList, error)
	PutUserBasicById(ctx context.Context, in *UpdateUserParams, opts ...grpc.CallOption) (*UserBasicInfo, error)
	PutUserPasswordById(ctx context.Context, in *UpdateUserParams, opts ...grpc.CallOption) (*UserBasicInfo, error)
	PutUserPasswordByEmail(ctx context.Context, in *UpdateUserParams, opts ...grpc.CallOption) (*UserBasicInfo, error)
}

type mySQLBindServiceClient struct {
	cc *grpc.ClientConn
}

func NewMySQLBindServiceClient(cc *grpc.ClientConn) MySQLBindServiceClient {
	return &mySQLBindServiceClient{cc}
}

func (c *mySQLBindServiceClient) NewOneUser(ctx context.Context, in *UserBasicInfo, opts ...grpc.CallOption) (*UserBasicInfo, error) {
	out := new(UserBasicInfo)
	err := c.cc.Invoke(ctx, "/pb.MySQLBindService/NewOneUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySQLBindServiceClient) GetUserById(ctx context.Context, in *QueryUserParams, opts ...grpc.CallOption) (*UserBasicInfo, error) {
	out := new(UserBasicInfo)
	err := c.cc.Invoke(ctx, "/pb.MySQLBindService/GetUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySQLBindServiceClient) GetUserByEmail(ctx context.Context, in *QueryUserParams, opts ...grpc.CallOption) (*UserBasicInfo, error) {
	out := new(UserBasicInfo)
	err := c.cc.Invoke(ctx, "/pb.MySQLBindService/GetUserByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySQLBindServiceClient) GetUsersByName(ctx context.Context, in *QueryUserParams, opts ...grpc.CallOption) (*UserBasicInfoList, error) {
	out := new(UserBasicInfoList)
	err := c.cc.Invoke(ctx, "/pb.MySQLBindService/GetUsersByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySQLBindServiceClient) PutUserBasicById(ctx context.Context, in *UpdateUserParams, opts ...grpc.CallOption) (*UserBasicInfo, error) {
	out := new(UserBasicInfo)
	err := c.cc.Invoke(ctx, "/pb.MySQLBindService/PutUserBasicById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySQLBindServiceClient) PutUserPasswordById(ctx context.Context, in *UpdateUserParams, opts ...grpc.CallOption) (*UserBasicInfo, error) {
	out := new(UserBasicInfo)
	err := c.cc.Invoke(ctx, "/pb.MySQLBindService/PutUserPasswordById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySQLBindServiceClient) PutUserPasswordByEmail(ctx context.Context, in *UpdateUserParams, opts ...grpc.CallOption) (*UserBasicInfo, error) {
	out := new(UserBasicInfo)
	err := c.cc.Invoke(ctx, "/pb.MySQLBindService/PutUserPasswordByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MySQLBindServiceServer is the server API for MySQLBindService service.
type MySQLBindServiceServer interface {
	NewOneUser(context.Context, *UserBasicInfo) (*UserBasicInfo, error)
	GetUserById(context.Context, *QueryUserParams) (*UserBasicInfo, error)
	GetUserByEmail(context.Context, *QueryUserParams) (*UserBasicInfo, error)
	GetUsersByName(context.Context, *QueryUserParams) (*UserBasicInfoList, error)
	PutUserBasicById(context.Context, *UpdateUserParams) (*UserBasicInfo, error)
	PutUserPasswordById(context.Context, *UpdateUserParams) (*UserBasicInfo, error)
	PutUserPasswordByEmail(context.Context, *UpdateUserParams) (*UserBasicInfo, error)
}

// UnimplementedMySQLBindServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMySQLBindServiceServer struct {
}

func (*UnimplementedMySQLBindServiceServer) NewOneUser(ctx context.Context, req *UserBasicInfo) (*UserBasicInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewOneUser not implemented")
}
func (*UnimplementedMySQLBindServiceServer) GetUserById(ctx context.Context, req *QueryUserParams) (*UserBasicInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}
func (*UnimplementedMySQLBindServiceServer) GetUserByEmail(ctx context.Context, req *QueryUserParams) (*UserBasicInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByEmail not implemented")
}
func (*UnimplementedMySQLBindServiceServer) GetUsersByName(ctx context.Context, req *QueryUserParams) (*UserBasicInfoList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersByName not implemented")
}
func (*UnimplementedMySQLBindServiceServer) PutUserBasicById(ctx context.Context, req *UpdateUserParams) (*UserBasicInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutUserBasicById not implemented")
}
func (*UnimplementedMySQLBindServiceServer) PutUserPasswordById(ctx context.Context, req *UpdateUserParams) (*UserBasicInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutUserPasswordById not implemented")
}
func (*UnimplementedMySQLBindServiceServer) PutUserPasswordByEmail(ctx context.Context, req *UpdateUserParams) (*UserBasicInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutUserPasswordByEmail not implemented")
}

func RegisterMySQLBindServiceServer(s *grpc.Server, srv MySQLBindServiceServer) {
	s.RegisterService(&_MySQLBindService_serviceDesc, srv)
}

func _MySQLBindService_NewOneUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBasicInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLBindServiceServer).NewOneUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MySQLBindService/NewOneUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLBindServiceServer).NewOneUser(ctx, req.(*UserBasicInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySQLBindService_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLBindServiceServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MySQLBindService/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLBindServiceServer).GetUserById(ctx, req.(*QueryUserParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySQLBindService_GetUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLBindServiceServer).GetUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MySQLBindService/GetUserByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLBindServiceServer).GetUserByEmail(ctx, req.(*QueryUserParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySQLBindService_GetUsersByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLBindServiceServer).GetUsersByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MySQLBindService/GetUsersByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLBindServiceServer).GetUsersByName(ctx, req.(*QueryUserParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySQLBindService_PutUserBasicById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLBindServiceServer).PutUserBasicById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MySQLBindService/PutUserBasicById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLBindServiceServer).PutUserBasicById(ctx, req.(*UpdateUserParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySQLBindService_PutUserPasswordById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLBindServiceServer).PutUserPasswordById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MySQLBindService/PutUserPasswordById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLBindServiceServer).PutUserPasswordById(ctx, req.(*UpdateUserParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySQLBindService_PutUserPasswordByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLBindServiceServer).PutUserPasswordByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MySQLBindService/PutUserPasswordByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLBindServiceServer).PutUserPasswordByEmail(ctx, req.(*UpdateUserParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _MySQLBindService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MySQLBindService",
	HandlerType: (*MySQLBindServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewOneUser",
			Handler:    _MySQLBindService_NewOneUser_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _MySQLBindService_GetUserById_Handler,
		},
		{
			MethodName: "GetUserByEmail",
			Handler:    _MySQLBindService_GetUserByEmail_Handler,
		},
		{
			MethodName: "GetUsersByName",
			Handler:    _MySQLBindService_GetUsersByName_Handler,
		},
		{
			MethodName: "PutUserBasicById",
			Handler:    _MySQLBindService_PutUserBasicById_Handler,
		},
		{
			MethodName: "PutUserPasswordById",
			Handler:    _MySQLBindService_PutUserPasswordById_Handler,
		},
		{
			MethodName: "PutUserPasswordByEmail",
			Handler:    _MySQLBindService_PutUserPasswordByEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mysqlBind.proto",
}
